version: 1

update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "stable-2.8"
    default_reviewers:
      - "MarkEWaite"
    default_labels:
      - "no-changelog"
